### ISSUE TITLE
Dont have Serial Number Register

### ISSUE THREAD

**Issue by lijc25** [Silverr12/DMA-CFW-Guide#17]
I use Arbor to read，the network controller ->  type 0 Header  dont have   Serial Number Register  ，pls see the screen picture
![image](https://github.com/user-attachments/assets/18f473a9-193f-4773-a5c0-57660cb2542c)

**Comment by Silverr12** [comment]
I'm sorry I'm not sure what you mean by serial number register and I don't see anything out of the ordinary in the image, do you mean the base address registers?

**Comment by Rakeshmonkee** [comment]
> I use Arbor to read，the network controller ->  type 0 Header  dont have   Serial Number Register  ，pls see the screen picture
> 
> ![image](https://github.com/user-attachments/assets/18f473a9-193f-4773-a5c0-57660cb2542c)
> 
> 

Do you mean device serial number?

**Comment by lijc25** [comment]
Sorry, i mean DSN cant found

**Comment by Silverr12** [comment]
That's alright, some devices indeed will not have a serial number, so in this case you'll have to just fully zero it out in the appropriate config line

**Comment by lijc25** [comment]
Thanks!
