### ISSUE TITLE
Would it work with CaptainDMA 35T?

### ISSUE THREAD

**Issue by erLCoder** [Silverr12/DMA-CFW-Guide#18]
I want to make emulated firmware using ur guide. Is it a great idea to play with it rust or any other eac and be games? And would it match with captaindma 35t?

**Comment by Silverr12** [comment]
Not that I endorse using it on games but theoretically if you do accomplish every step it would work yes, additionally there are other prebuilt DMA firmware projects from other talented individuals you could find here on github that would work out-of-the-box for you too. As for the CapDMA 35t you would use the squirrel files as in the guide
