### ISSUE TITLE
Discord? 

### ISSUE THREAD

**Issue by Badrodro** [Silverr12/DMA-CFW-Guide#2]
Hello sir, great work ! 
Can i have your  discord to contact u ?

**Comment by Silverr12** [comment]
sure, its `desilvered`

**Comment by uberhalit** [comment]
> sure, its `desilvered`

@Silverr12 seems like you set friend requests policy to none 😢

**Comment by Silverr12** [comment]
> > sure, its `desilvered`
> 
> @Silverr12 seems like you set friend requests policy to none 😢

Yep sorry in between the time I originally posted that and now I couldn't keep up with the influx haha, you should still be able to message me if you join the server I've got linked near the bottom, apologies again
