### ISSUE TITLE
Some basic questions

### ISSUE THREAD

**Issue by Jotalz** [Silverr12/DMA-CFW-Guide#4]
I'm trying to follow the tutorial to understand and make my own firmware,due to lack of relevant knowledge, I would like to ask that
![a](https://github.com/Silverr12/DMA-CFW-Guide/assets/57427866/fa3536d7-0859-4667-9584-5b644365eb98)
Does this mean the firmware used by each model of dma card is specific as mentioned in the article with these three names?If not, then how can I tell which firmware the dma card I purchased uses?

**Comment by Rakeshmonkee** [comment]
if you have a 35T, use squirrel
if you have a 75T, use EnigmaX1
if you have 100T, use ZDMA

**Comment by Jotalz** [comment]
Thanks, got it! I'm curious if something like this will happen with 35T:EnigmaX1

**Comment by Rakeshmonkee** [comment]
> Does this mean the firmware used by each model of dma card is specific as mentioned in the article with these three names?

it says in the picture "use the corresponding folder for your DMA card"

**Comment by Rakeshmonkee** [comment]
> Thanks, got it! I'm curious if something like this will happen with 35T:EnigmaX1

35T can't support EnigmaX1
