### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by w6rldsss** [Silverr12/DMA-CFW-Guide#5]
first question, do  I need any specific type of motherboard for this? Second question. will this work as a donor card? https://www.amazon.com/FebSmart-Wireless-300Mbps-Network-FS-N300/dp/B07MHB2R2V 

Wireless N 2.4GHz 300Mbps PCIE Wireless Network Adapter for Windows 11, 10, 8.1, 8, 7, XP (32/64bit), Windows Server and Linux PCs, PCIE WiFi Card, PCIE WiFi Adapter (FS-N300)

these are probably some stupid questions sorry lol.

**Comment by w6rldsss** [comment]
and one more question do i have to use the donor card on the second pc only because my  second pc is a laptop.
am i only risking getting banned in a game if i dont use it on my second pc?

**Comment by Rakeshmonkee** [comment]
> first question, do  I need any specific type of motherboard for this? Second question. will this work as a donor card? https://www.amazon.com/FebSmart-Wireless-300Mbps-Network-FS-N300/dp/B07MHB2R2V 
> 
> 
> 
> Wireless N 2.4GHz 300Mbps PCIE Wireless Network Adapter for Windows 11, 10, 8.1, 8, 7, XP (32/64bit), Windows Server and Linux PCs, PCIE WiFi Card, PCIE WiFi Adapter (FS-N300)
> 
> 
> 
> these are probably some stupid questions sorry lol.

1. Preferably an MSI motherboard. Since there are less issues with the mobo and configspace of dma. Make sure it has pcie slot.

2. Yes, that will work

**Comment by Rakeshmonkee** [comment]
> and one more question do i have to use the donor card on the second pc only because my  second pc is a laptop.
> 
> am i only risking getting banned in a game if i dont use it on my second pc?

Donor card goes into main pc to get values, then you switch to dma once you've built the fw. If this isn't what you are asking, please be more clear and specific in your question

**Comment by Rakeshmonkee** [comment]
closing issue since no response in 11 hours
