### ISSUE TITLE
about  Valorant

### ISSUE THREAD

**Issue by xdx666666** [Silverr12/DMA-CFW-Guide#7]
Can he solve Valorant, please?

**Comment by Rakeshmonkee** [comment]
> Can he solve Valorant, please?

Huh?

**Comment by Silverr12** [comment]
I'm sorry I won't be posting any valorant bypasses publicly, thats a sure-fire way to get it patched.

If you mess around with your own firmware and experiment you should be able to find one relatively easily.

**Comment by xdx666666** [comment]
@Silverr12 Thanks, I guess I should try it, also, discord doesn't seem to get in, is there any telegram please?

**Comment by Silverr12** [comment]
No telegram my apologies, the discord is currently my only fw community
