### ISSUE TITLE
DSN reverse

### ISSUE THREAD

**Issue by Shiro1999** [Silverr12/DMA-CFW-Guide#8]
Serial Number Register (Lower DW): 68 4C E0 00
Serial Number Register (Upper DW): 01 00 00 00
Combine yours in the same format:
Lower DW + Upper DW = 68 4C E0 00 01 00 00 00
That' right.
However, I checked the Device Manager, and found that it should be
rw[127:64]  <= 64'h01000000684CE000.

**Comment by Silverr12** [comment]
Ah you're actually not the first person to raise this issue to me, I have just forgotten to update it, thank you either way for reminding me I'll switch them around now
